version: "3"

services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:8080' # Public HTTP Port
      - '81:8181' # Admin Web Port
      - '443:4443' # Public HTTPS Port

    environment:
      # TODO check this
      DISABLE_IPV6: 'true'

    volumes:
      - ./nginx-proxy-manager:/config:rw